// Admin antifraud queue (route "/antifraud"). Cases are generated by explicit
// server rules and remain review-only until an authenticated admin records a
// decision. No raw CPF/CNH/Pix value or precise coordinate is rendered here.

import { useCallback, useEffect, useState } from 'react';
import {
  Pressable,
  RefreshControl,
  ScrollView,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import Header from '../../components/Header';
import AppCard from '../../components/AppCard';
import AppBadge from '../../components/AppBadge';
import AppButton from '../../components/AppButton';
import AppInput from '../../components/AppInput';
import { colors } from '../../constants/colors';
import { spacing, radius } from '../../constants/spacing';
import { typography, fontFamily } from '../../constants/typography';
import { showConfirmAlert } from '../../utils/alertUtils';
import {
  listAdminRiskCases,
  decideAdminRiskCase,
} from '../../services/adminService';

const FILTERS = [
  { key: 'open', label: 'Novos' },
  { key: 'under_review', label: 'Em análise' },
  { key: 'resolved', label: 'Resolvidos' },
  { key: 'fraud_confirmed', label: 'Fraude confirmada' },
  { key: 'all', label: 'Todos' },
];

const REASON_LABELS = {
  COMMISSION_HOLD_STALE: 'Comissão retida há muito tempo',
  COMMISSION_NOT_SETTLED: 'Comissão sem liquidação',
  COMMISSION_CAPTURE_EXCEEDS_HOLD: 'Captura maior que a retenção',
  WALLET_LEDGER_MISMATCH: 'Carteira diferente do extrato',
  PAYMENT_DISPUTE_OPENED: 'Disputa de pagamento',
  PASSENGER_FALSE_PAYMENT_PATTERN: 'Padrão de falso pagamento',
  DRIVER_NON_RECEIPT_PATTERN: 'Padrão de não recebimento',
  REPEATED_CANCELLATIONS: 'Cancelamentos repetidos',
  PASSENGER_NO_SHOW: 'Passageiro ausente',
  REPEATED_DRIVER_PASSENGER_PAIR: 'Par motorista/passageiro recorrente',
  SUSPICIOUS_RIDE_DURATION: 'Duração de corrida suspeita',
  IMPOSSIBLE_GPS_SPEED: 'Velocidade GPS impossível',
  DUPLICATE_CPF: 'CPF já utilizado',
  DUPLICATE_CNH: 'CNH já utilizada',
  DUPLICATE_CRLV: 'CRLV já utilizado',
  DUPLICATE_VEHICLE_PLATE: 'Placa já utilizada',
  DUPLICATE_PIX_KEY: 'Chave Pix já utilizada',
  DUPLICATE_PHONE: 'Telefone já utilizado',
  DUPLICATE_EMAIL: 'E-mail já utilizado',
  PROMOTION_ABUSE_PATTERN: 'Possível abuso de promoção',
};

function severityTone(severity) {
  if (severity === 'critical') return 'danger';
  if (severity === 'high') return 'warning';
  return 'neutral';
}

function severityLabel(severity) {
  const labels = {
    critical: 'Crítico',
    high: 'Alto',
    medium: 'Médio',
    low: 'Baixo',
  };
  return labels[severity] || 'Baixo';
}

function statusLabel(status) {
  const labels = {
    open: 'Novo',
    under_review: 'Em análise',
    resolved: 'Resolvido',
    closed_no_evidence: 'Sem evidência',
    fraud_confirmed: 'Fraude confirmada',
  };
  return labels[status] || status || 'Novo';
}

function actorLabel(actorType) {
  if (actorType === 'driver') return 'Motorista';
  if (actorType === 'passenger') return 'Passageiro';
  return 'Sistema';
}

function formatDateTime(epochMs) {
  if (!Number(epochMs || 0)) return '—';
  return new Intl.DateTimeFormat('pt-BR', {
    dateStyle: 'short',
    timeStyle: 'short',
    timeZone: 'America/Fortaleza',
  }).format(new Date(Number(epochMs)));
}

function RiskCaseCard({ entry, expanded, onToggle, onDecide, submitting, router }) {
  const [reasonCode, setReasonCode] = useState('ADMIN_REVIEW');
  const [note, setNote] = useState('');
  const [restrictionHours, setRestrictionHours] = useState('24');
  const reasonLabel = REASON_LABELS[entry.primaryReasonCode]
    || entry.primaryReasonCode
    || 'Sinal não classificado';

  function submit(outcome) {
    if (!reasonCode.trim()) return;
    onDecide({
      caseId: entry.caseId,
      outcome,
      reasonCode: reasonCode.trim(),
      note: note.trim() || null,
      restrictionHours: outcome === 'temporary_restriction'
        ? Number(restrictionHours || 24)
        : null,
    });
  }

  function confirmFraud() {
    showConfirmAlert({
      title: 'Confirmar fraude?',
      message: 'Esta decisão bloqueia novas corridas da conta. O histórico e as retenções financeiras não são apagados.',
      confirmText: 'Confirmar fraude',
      destructive: true,
      onConfirm: () => submit('fraud_confirmed'),
    });
  }

  return (
    <AppCard>
      <Pressable onPress={onToggle} style={{ gap: spacing.sm }}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }}>
          <View style={{ flex: 1, gap: spacing.xs }}>
            <Text style={[{ fontFamily, color: colors.text }, typography.bodyBold]}>{reasonLabel}</Text>
            <Text style={[{ fontFamily, color: colors.textMuted }, typography.small]}>
              {actorLabel(entry.actorType)} · origem {entry.sourceType || '—'}
            </Text>
          </View>
          <View style={{ alignItems: 'flex-end', gap: spacing.xs }}>
            <AppBadge label={severityLabel(entry.severity)} tone={severityTone(entry.severity)} />
            <AppBadge label={statusLabel(entry.status)} tone={entry.status === 'fraud_confirmed' ? 'danger' : 'neutral'} />
          </View>
        </View>
        <Text style={[{ fontFamily, color: colors.textFaint }, typography.caption]}>
          Aberto em {formatDateTime(entry.openedAtMs)} · {entry.linkedEventCount || 0} sinal(is)
        </Text>
        <Text style={[{ fontFamily, color: colors.primary }, typography.small]}>
          {expanded ? 'Fechar detalhes ▲' : 'Analisar caso ▼'}
        </Text>
      </Pressable>

      {expanded ? (
        <View style={{ gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.md }}>
          <View style={{ gap: spacing.xs }}>
            <Text style={[{ fontFamily, color: colors.textMuted }, typography.small]}>
              Ação sugerida: {entry.recommendedAction || 'revisar'}
            </Text>
            <Text style={[{ fontFamily, color: colors.textMuted }, typography.small]}>
              Fonte: {entry.sourceType || '—'} / {entry.sourceId || '—'}
            </Text>
            {entry.decision ? (
              <Text style={[{ fontFamily, color: colors.textMuted }, typography.small]}>
                Última decisão: {entry.decision.outcome || '—'} · {entry.decision.reasonCode || '—'}
              </Text>
            ) : null}
          </View>

          {entry.actorType === 'driver' ? (
            <AppButton
              title="Abrir cadastro do motorista"
              variant="secondary"
              onPress={() => router.push({
                pathname: '/(admin)/driver-detail',
                params: { driverId: entry.actorId },
              })}
            />
          ) : null}
          {entry.sourceType === 'ride' && entry.sourceId ? (
            <AppButton
              title="Abrir corrida relacionada"
              variant="secondary"
              onPress={() => router.push({
                pathname: '/(admin)/ride-detail',
                params: { rideId: entry.sourceId },
              })}
            />
          ) : null}

          <AppInput
            label="Código da decisão"
            value={reasonCode}
            onChangeText={setReasonCode}
            placeholder="Ex.: DOCUMENTO_CONFIRMADO"
          />
          <AppInput
            label="Observação admin"
            value={note}
            onChangeText={setNote}
            placeholder="Explique a evidência e a decisão"
          />
          <AppInput
            label="Horas de restrição temporária"
            value={restrictionHours}
            onChangeText={setRestrictionHours}
            keyboardType="number-pad"
            placeholder="24"
          />

          <View style={{ gap: spacing.sm }}>
            <AppButton
              title="Marcar em análise"
              variant="secondary"
              disabled={submitting}
              onPress={() => submit('mark_under_review')}
            />
            <AppButton
              title="Registrar advertência"
              variant="secondary"
              disabled={submitting}
              onPress={() => submit('warning_recorded')}
            />
            <AppButton
              title="Restringir novas corridas temporariamente"
              disabled={submitting}
              onPress={() => submit('temporary_restriction')}
            />
            <AppButton
              title="Encerrar sem evidência"
              variant="ghost"
              disabled={submitting}
              onPress={() => submit('close_no_evidence')}
            />
            <Pressable
              onPress={confirmFraud}
              disabled={submitting}
              style={{
                borderWidth: 1,
                borderColor: colors.danger,
                borderRadius: radius.md,
                paddingVertical: spacing.md,
                alignItems: 'center',
                opacity: submitting ? 0.5 : 1,
              }}
            >
              <Text style={[{ fontFamily, color: colors.danger }, typography.bodyBold]}>
                Confirmar fraude e bloquear novas corridas
              </Text>
            </Pressable>
          </View>
        </View>
      ) : null}
    </AppCard>
  );
}

export default function AntifraudAdmin() {
  const router = useRouter();
  const [filter, setFilter] = useState('open');
  const [cases, setCases] = useState([]);
  const [expandedId, setExpandedId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [truncated, setTruncated] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const result = await listAdminRiskCases(filter, 100);
      setCases(result?.cases || []);
      setTruncated(result?.truncated === true);
      console.log('[ADMIN_RISK] cases loaded', {
        filter,
        count: result?.cases?.length || 0,
        truncated: result?.truncated === true,
      });
    } catch (e) {
      console.log('[ADMIN_RISK] cases load error', { code: e?.code, message: e?.message });
      setError('Não foi possível carregar os casos antifraude.');
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => {
    load();
  }, [load]);

  async function decide(payload) {
    setSubmitting(true);
    setError('');
    try {
      console.log('[ADMIN_RISK] decision requested', {
        caseId: payload.caseId,
        outcome: payload.outcome,
        reasonCode: payload.reasonCode,
      });
      await decideAdminRiskCase(payload);
      setExpandedId(null);
      await load();
    } catch (e) {
      console.log('[ADMIN_RISK] decision error', {
        caseId: payload.caseId,
        outcome: payload.outcome,
        code: e?.code,
        message: e?.message,
      });
      setError('A decisão não foi aplicada. Verifique o caso e tente novamente.');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }} edges={['top', 'bottom']}>
      <ScrollView
        refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}
        contentContainerStyle={{ padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxl }}
      >
        <Header title="Antifraude" subtitle="Fila de revisão explicável" onBack={() => router.back()} />

        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}>
          {FILTERS.map((item) => {
            const selected = item.key === filter;
            return (
              <Pressable
                key={item.key}
                onPress={() => setFilter(item.key)}
                style={{
                  borderRadius: radius.pill,
                  borderWidth: 1,
                  borderColor: selected ? colors.primary : colors.border,
                  backgroundColor: selected ? colors.primary : colors.card,
                  paddingHorizontal: spacing.md,
                  paddingVertical: spacing.sm,
                }}
              >
                <Text
                  style={[
                    { fontFamily, color: selected ? colors.onPrimary : colors.textMuted },
                    typography.small,
                  ]}
                >
                  {item.label}
                </Text>
              </Pressable>
            );
          })}
        </View>

        {error ? (
          <AppCard>
            <Text style={[{ fontFamily, color: colors.danger }, typography.small]}>{error}</Text>
          </AppCard>
        ) : null}

        {truncated ? (
          <AppCard>
            <Text style={[{ fontFamily, color: colors.warning }, typography.small]}>
              A fila atingiu o limite de segurança de leitura. Os casos mais recentes devem ser tratados primeiro.
            </Text>
          </AppCard>
        ) : null}

        {!loading && cases.length === 0 ? (
          <AppCard>
            <Text style={[{ fontFamily, color: colors.textMuted }, typography.body]}>
              Nenhum caso nesta categoria.
            </Text>
          </AppCard>
        ) : null}

        {cases.map((entry) => (
          <RiskCaseCard
            key={entry.caseId}
            entry={entry}
            expanded={expandedId === entry.caseId}
            onToggle={() => setExpandedId(expandedId === entry.caseId ? null : entry.caseId)}
            onDecide={decide}
            submitting={submitting}
            router={router}
          />
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}
