// @ts-check
// DriveLocal launch antifraud vocabulary. Keep rules explicit and explainable:
// no opaque AI score, no permanent automatic block, and no sensitive values in
// risk metadata or logs.

const COLLECTIONS = Object.freeze({
  RISK_EVENTS: 'riskEvents',
  RISK_PROFILES: 'riskProfiles',
  FRAUD_CASES: 'fraudCases',
  FINANCIAL_ALERTS: 'financialAlerts',
  SYSTEM_HEALTH: 'systemHealth',
  OPERATIONAL_SNAPSHOTS: 'operationalSnapshots',
});

const SEVERITY = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
});

const ACTION = Object.freeze({
  LOG_ONLY: 'log_only',
  WARN: 'warn',
  REQUIRE_REVIEW: 'require_review',
  TEMPORARY_RESTRICTION: 'temporary_restriction',
  BLOCK_NEW_RIDES: 'block_new_rides',
  BLOCK_NEW_ACCEPTANCES: 'block_new_acceptances',
  FREEZE_SETTLEMENT: 'freeze_settlement',
  ADMIN_SUSPENSION: 'admin_suspension',
});

const ACTOR_TYPE = Object.freeze({
  DRIVER: 'driver',
  PASSENGER: 'passenger',
  SYSTEM: 'system',
  ADMIN: 'admin',
});

const REASON = Object.freeze({
  COMMISSION_HOLD_STALE: 'COMMISSION_HOLD_STALE',
  COMMISSION_NOT_SETTLED: 'COMMISSION_NOT_SETTLED',
  COMMISSION_CAPTURE_EXCEEDS_HOLD: 'COMMISSION_CAPTURE_EXCEEDS_HOLD',
  COMMISSION_ZERO_WITHOUT_VALID_FREE_POLICY: 'COMMISSION_ZERO_WITHOUT_VALID_FREE_POLICY',
  WALLET_LEDGER_MISMATCH: 'WALLET_LEDGER_MISMATCH',
  WALLET_NEGATIVE: 'WALLET_NEGATIVE',
  DUPLICATE_WALLET_TRANSACTION: 'DUPLICATE_WALLET_TRANSACTION',
  PAYMENT_DISPUTE_OPENED: 'PAYMENT_DISPUTE_OPENED',
  REPEATED_PAYMENT_DISPUTES: 'REPEATED_PAYMENT_DISPUTES',
  PASSENGER_FALSE_PAYMENT_PATTERN: 'PASSENGER_FALSE_PAYMENT_PATTERN',
  DRIVER_NON_RECEIPT_PATTERN: 'DRIVER_NON_RECEIPT_PATTERN',
  PASSENGER_LATE_CANCELLATION: 'PASSENGER_LATE_CANCELLATION',
  DRIVER_LATE_CANCELLATION: 'DRIVER_LATE_CANCELLATION',
  REPEATED_CANCELLATIONS: 'REPEATED_CANCELLATIONS',
  PASSENGER_NO_SHOW: 'PASSENGER_NO_SHOW',
  REPEATED_DRIVER_PASSENGER_PAIR: 'REPEATED_DRIVER_PASSENGER_PAIR',
  SUSPICIOUS_RIDE_DURATION: 'SUSPICIOUS_RIDE_DURATION',
  IMPOSSIBLE_GPS_SPEED: 'IMPOSSIBLE_GPS_SPEED',
  ARRIVAL_TOO_FAR_FROM_PICKUP: 'ARRIVAL_TOO_FAR_FROM_PICKUP',
  COMPLETION_TOO_FAR_FROM_DESTINATION: 'COMPLETION_TOO_FAR_FROM_DESTINATION',
  DUPLICATE_CPF: 'DUPLICATE_CPF',
  DUPLICATE_CNH: 'DUPLICATE_CNH',
  DUPLICATE_CRLV: 'DUPLICATE_CRLV',
  DUPLICATE_VEHICLE_PLATE: 'DUPLICATE_VEHICLE_PLATE',
  DUPLICATE_PIX_KEY: 'DUPLICATE_PIX_KEY',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  MULTIPLE_ACCOUNTS_SAME_DEVICE: 'MULTIPLE_ACCOUNTS_SAME_DEVICE',
  DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',
  REPEATED_DOCUMENT_CHANGES: 'REPEATED_DOCUMENT_CHANGES',
  PROMOTION_CONFIGURATION_ERROR: 'PROMOTION_CONFIGURATION_ERROR',
  PROMOTION_ABUSE_PATTERN: 'PROMOTION_ABUSE_PATTERN',
  ROBOT_DRIVER_PRODUCTION_ATTEMPT: 'ROBOT_DRIVER_PRODUCTION_ATTEMPT',
  ACCOUNT_SUSPENSION_BYPASS_ATTEMPT: 'ACCOUNT_SUSPENSION_BYPASS_ATTEMPT',
});

const RULE_VERSION = 'launch-2026.1';

module.exports = {
  COLLECTIONS,
  SEVERITY,
  ACTION,
  ACTOR_TYPE,
  REASON,
  RULE_VERSION,
};
